import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

interface RootLayoutProps {
  children: React.ReactNode;
  chat: React.ReactNode;
}

export default function RootLayout({
  children,
  chat,
}: Readonly<RootLayoutProps>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <Providers>
            {children}
            {chat}
            <Toaster position="bottom-right" richColors />
          </Providers>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
